### ISSUE TITLE
Requirements Elicitation on reviewing the SOW by Member (Siddhi)

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#11]
This is an activity that is created for the purpose of completion of Epic #6 
In this Activity, as a member of the organization, @sshidruk0721 will go through the "Statement of the Work" document and list out the requirements that she feels the "SUS" software system needs considering the "Statement of the Work" document

**Comment by Amitejashrout99** [comment]
@sshidruk0721, please create a separate task under this activity and label as "Task". If the "Task" label doesn't exist, ask @marcandru to create one. After your analysis, post your requirements in the comment section.

**Comment by sshidruk0721** [comment]
#11
### List of requirements according to the Statement of the Work document: 

**_ADMIN Requirements:_**

As an admin, I should have access to a list of all instructors with their contact information

As an admin, I should review enrollment requests from students

As an admin, I should be able to view, add, edit, or remove courses from the system.

As an admin, I should receive notification when a course reaches 80% enrollment from the system.

As an admin, I should be able to add/remove students from a class so that a waitlisted student can register.

_**Student, Instructor and TA Requirements:**_

As a student, I should be able to attend lectures virtually

As a student, I should be able to view my grades to can check my progress.

As a student, I should be able to see the locations of the class so that I can choose the lecture location easily according to my convenience.

As a student, I should be able to communicate with other group member and also their information should be visible to me.

As a student, I should be able to submit a request for the prerequisite wavier.

As a student, I should be notified on their university email whenever the instructor posts an announcement.

As an instructor, I should be able to view the grade of each assignment to track of class performance. 

As an instructor, I want to manage access to modify information if there is any change.

As an instructor, I should be able to view student's information.

As a TA, I should be able to enter grades into the system in bulk so that the students can view their grades.

**Comment by sshidruk0721** [comment]
#11
### List of requirements according to the Statement of the Work document: 

**Admin Requirements:**

- View, add, edit, or remove courses from the system.
- Receive notification when a course reaches 80% enrollment from the system.
- Add/remove students from a class.
- Access the list of all instructors for their information.
- Ability to review of enrollment requests from students.

**Instructor and TA Requirements**

- View the grades of all assignment to track of class performance. 
- Manage access to modify information if there is any change.
- Permission to view student's information.
- Ability to enter grades in bulk at one time.

**Student**
- View grades to monitor progress.
- Ability to view locations to plan class selection.
- Submit a request for the prerequisite wavier.
- Get notified on email for important updates.
- Ability to communicate with other group member.

**Comment by sshidruk0721** [comment]
Closing this activity on completion of Task #48
